### ISSUE TITLE
Cohorts

### ISSUE THREAD

**Issue by ericdouglas** [ossu/roadmap#11]
- [Example](https://chingu-cohorts.github.io/chingu-directory/)
- [Discusson](https://gitter.im/open-source-society/computer-science?at=59d41c66177fb9fe7e365a77)

**Comment by amorriscode** [comment]
I am willing to do whatever I have to to make this work. For me, this is the biggest challenge with sticking to the program. I also know a few folks who have tried self-study/MOOCs and this has been their biggest challenge, and often their cause for failure.

**Comment by ericdouglas** [comment]
@amorriscode that's awesome. I have one idea to implement this:

We can create a `cohorts` repository, and when a student wants to start a new course and connect with others doing the same one, s/he can go to the cohorts repo and find in the issues if there is some issue opened with the name of the course s/he is about to start.

If there is no group yet, s/he can create one.

Ideally, any new group should have at least 2 "coordinators", that are students that will have the responsibility to check with other students if they are having problems; they will help everyone to succeed. If someone doesn't appear in the meeting scheduled, the coordinators will contact them to see what happened and so on. This is a way to have everyone motivated and engaged with the final goal - finish the course.

In the end of the course, students of the group can pair to create the final project.

We should also think in a way to formalize it and make a simple reproducible step-by-step guide to create start a new cohort, with general guidance on this for students and coordinators.

**Comment by amorriscode** [comment]
I like the idea of a `cohorts` repository. It would be a good place for us to list the information of current students in the cohort (location, contact info, etc).

I like the idea of cohort "coordinators" but this might be one of the most difficult parts. How do we motivate or know when a student is willing to coordinate to the end of the cohort? I am definitely willing to champion any cohorts I am apart of. I am even willing to do my best champion this features as it rolls out (ie: check in with coordinators, etc).

One of my favourite features is the ability for students to form groups and build projects together. Building together is essential for levelling up as a developer.

In regards to formalization and making new cohorts easy to startup, we could use a form when a user wants to generate a new cohort. [This form](https://elementui.github.io/issue-generator) comes to mind. This can help auto-generate some templates for keeping track of relevant cohort information.

**Comment by ericdouglas** [comment]
> I like the idea of a cohorts repository. It would be a good place for us to list the information of current students in the cohort (location, contact info, etc).

Cool. We can create folders for each curriculum (`bioinformatics`, `computer-science`, `data-science`, etc) and inside each folder, more folders with the name of the courses (`algorithms-i`, etc...), and inside each of them one markdown file with the info of the cohort (coordinators, students, final projects, etc).

```
computer-science/
    algorithms-i/
        cohort-0001.md
        cohort-0002.md
```

> How do we motivate or know when a student is willing to coordinate to the end of the cohort?

We don't :)

For that reason, I would sincerely suggest to only allow a new cohort when we have **at least 3** coordinators, so if one has some problem, the remaining coordinators can invite a new one.

> I am definitely willing to champion any cohorts I am apart of. I am even willing to do my best champion this features as it rolls out (ie: check in with coordinators, etc).

That'll be amazing! And we can implement the "3 coordinators rule" to all OSSU initiatives, so you will have at least 2 more helping you check in with coordinators as well.

> Building together is essential for levelling up as a developer.

Yeah, totally agree!

> In regards to formalization and making new cohorts easy to startup, we could use a form when a user wants to generate a new cohort. This form comes to mind.

Looks great! We surely can use it.

I'll create the cohorts repo now and invite you to our org and put you as a maintainer of it so we can start to play with it a little :)

**Comment by amorriscode** [comment]
So I think the workflow would be something like below:

1. Student requests a cohort (Github issue in the repo), if one doesn't already exist, using our cohort form
2. Once 3 students comment on that cohort/issue, a maintainer will create a new `.md` file for their cohort
3. The issue gets closed
4. Students then make a PR to their respective cohort file so we can add their student information

What do you think about that?

**Comment by ericdouglas** [comment]
1. Agreed
1. Here one of the coordinators (a student) can create the file and submit a PR
1. The issue gets closed when the cohort is complete (let's say when 5 or 10 students comments on the issue, depending on the size of the cohort)
1. Agreed

Makes sense these additions?

**Comment by amorriscode** [comment]
I like the additions. We will have to come up with some guidelines on what "complete" means. We definitely will want to clean up inactive cohorts where people don't end up finishing. That'll be the beauty of coordinators though; we can reach out to them for statuses if need be.

**Comment by ericdouglas** [comment]
> We will have to come up with some guidelines on what "complete" means.

Yeah, for sure.

Some ideas:

- Size:
  - Min: 5
  - Max: 20
- Duration (of the issue - before actually start the studies): 2 weeks
- Planning: `n` sections/videos/chapters to study per week/month
- More...

**Comment by amorriscode** [comment]
For next steps, if you'd like, I can submit a PR to the `cohorts` repo with all three paths and the classes within them. I can also look into building a form to request issues.

**Comment by ericdouglas** [comment]
You are the founder of this project and the main maintainer. I'll help you on it in the best way I can, being a maintainer as well, but please feel free to do whatever you think is necessary to accomplish our goal to create this framework for all OSSU students.

You don't need to ask for permission! But feel free to ping me to discuss ideas, I'm totally open to helping on this.

I'm really glad you're willing to help on this since I believe it'll be a really, really key feature for OSSU.

Let's do this! :fist_oncoming:

**Comment by ericdouglas** [comment]
@amorriscode You told about your coworker that wants to help on this as well. If you tell me his/her username I can invite him/her to our org as well.

I just add the [cohorts section](https://github.com/ossu/contributors#cohorts) in the `contributors` repo :tada:

**Comment by amorriscode** [comment]
@ericdouglas What I meant was I have a coworker (maybe a few) that want to do the course, and could be candidates for the first cohort, haha. That was my miscommunication, whoops!

**Comment by ericdouglas** [comment]
Oh, ok haha :sweat_smile: 

Let's see if we find another person interested to help on this.

Maybe @shailalias @hamzicabdulah or @jeanleonino would like to be part of it? Feel free to skip the invite too friends :)

**Comment by amorriscode** [comment]
@ericdouglas Would it be beneficial to have a Slack channel? It would give cohorts a location for asynchronous communication, plus another support channel. I know we have Gitter but it seems like Slack might have a useful expanded feature list. I noticed a few other courses doing this, Coecadamy being one of them.

**Comment by scamargo** [comment]
@amorriscode could you elaborate on what you meant by duration above?

**Comment by amorriscode** [comment]
@scamargo Do you mean what @ericdouglas  said about duration? I think he was saying two weeks after creating a new cohort, the students begin studying (allowing others time to join in before it gets going).

I don't recall mentioning duration myself.

**Comment by scamargo** [comment]
@amorriscode yes you're right and thanks for the clarification.

I'm happy to help as a coordinator for a new cohort. My availability on personally going through the courses will be a a little limited between Oct 20-Nov20, but not so limited that I cant help as a coordinator during that time.

**Comment by ericdouglas** [comment]
@amorriscode for asynchronous communication I believe chat apps are not ideal in our specific scenario. In that case, a forum-like app is the most indicated. Some ideas to address this point:

- Group can talk in the issue they started, even with it closed (because closed means it already started).
- We need to unify our forum platforms (today we're using Google Groups and Reddit). In that sense, I believe Discourse will be a great solution. Each cohort could open a topic there and use it to communicate.

I'd stick with GH though. It's simple and has great support for code snippets and has a good notification system, where we can opt to Unsubscribe. With the Discourse solution, every time someone comments on it, the topic will be up in the list of recent topics, but it only interests for those in the cohort, so the GH solution looks ideal for me.

Also, another benefit of a forum-like app for this is that other students can find about the same doubt in the forum for example (discoverability).

The ideal usage of a forum + cohort channel IMO would be: if a student has some doubt, s/he open a topic in our forum (discourse for example), and maybe copy the link and send it to people of his/her cohort, through gitter via DM, telegram/whatsapp cohort group, or here in the cohort issue.

We should also encourage people to use StackOverflow for example, so the information we generate can be as useful, open and generic as possible.

Those are some ideas, let's iterate on it to find an optimal solution.

@scamargo by "duration" I meant "enrollment period". Let's say we have a cohort with `min` size of 5 and `max` size of 20 students, with an `enrollment period` of 14 days. After this period, if we have at least 5 students we can start the cohort.

About you being a coordinator, that's awesome! Start to watch [this](https://github.com/ossu/cohorts) repo so you can see when the first cohort will be open so you can see it and offer to be one of the coordinators.

**Comment by amorriscode** [comment]
@ericdouglas I think Discourse is probably a good idea. I agree that we can just keep the real time chat through Gitter DM, Telegram/WhatsApp, or whatever the cohort decides themselves.

One issue I have with GH is issues can get overwhelmingly long with a lot of back and forth. 

On another note, can you add the Cohorts team to the Cohorts repo? I'd like to push up my first commit but don't have the proper permissions on that repo.

**Comment by ericdouglas** [comment]
> One issue I have with GH is issues can get overwhelmingly long with a lot of back and forth.

Yeah, but is also annoying to stay one day off and when you return there are 500+ unread messages haha And the worst scenario is when we pass the 10k limit on Slack so messages start to disappear.

> On another note, can you add the Cohorts team to the Cohorts repo?

Oh, sorry. Done :white_check_mark: 

About the course's ID, that's a good idea, but we need to think in a pattern.

```
000-000-000-00000

curriculum-section-subsection-courseID
```

**Comment by amorriscode** [comment]
> About the course's ID, that's a good idea, but we need to think in a pattern.

I think the pattern you proposed is a good one. I will get the structure setup tomorrow ignoring the codes for the paths that don't have them, then I will add them once we figure that part out.

**Comment by ericdouglas** [comment]
To expand a little more about the pattern above:

**Curriculum** (by order of creation):

- `000`: Computer Science
- `001`: Data Science
- `002`: Bioinformatics

**Section** (each curriculum has its own sections):

- CS sections:
  - `000`: Introduction to Computer Science
  - `001`: Core CS
  - `002`: Advanced CS
  - `003`: Pro CS

**Subsection** (each curriculum has its own subsections):

- CS - Core CS subsections:
  - `000`: Core programming
  - `001`: Core math
  - `002`: Core systems
  - `003`: Core theory
  - `004`: Core applications

**Course IDs** (each curriculum has its own course ids):

- `00000`: Introduction to Computer Science - CS50
- `00001`: Introduction to Computer Science and Programming using Python
- `00002`: How to Code - Simple Data

With this format, maybe the `cohourts` repo structure could be:

```
README.md
bioinformatics/
    002-000-000-00000/
        cohort-0000.md
computer-science/
    000-000-000-00000/
        cohort-0000.md
        cohort-0001.md
    000-000-000-00001/
        cohort-0000.md
        cohort-0001.md
```

If we adopt this pattern, we need to add a column `ID` in the curriculum.

**Comment by amorriscode** [comment]
This seems simple, and I can implement it, my biggest issue is being having to figure out these codes in order to find them in the folder structure. Having the column `ID` will help, of course, but it would be nice of they were readable like regular university courses.

**Comment by ericdouglas** [comment]
Yes, this pattern is pretty cryptic haha Let's think in a higher-level pattern.

**Comment by scamargo** [comment]
I like that structure. 

Another thought is that students will benefit the most from cohorts that go at a pace that works for them. Cohort organizers should make the intended pace of the coursework clear in the readme before the enrollment period starts.

Specifically, organizers should capture the completion date for the course and perhaps also a high-level breakdown of the proposed schedule. The goal is that there would be a nice mix of accelerated & non-accelerated cohorts based on the demands from incoming students.

**Comment by scamargo** [comment]
Less cryptic alternative:

CS-Intro-Math-CS50

or even

CS-Intro-Math-00001

(leaning towards the first)

**Comment by amorriscode** [comment]
@scamargo I prefer this a lot more to the cryptic version proposed above. There is only one thing I'd like to see standardized across the paths if possible.

Bioinformatics has the section as years (1st year, 2nd year, etc). Computer science has the section as groupings (Intro, Core, Advanced, etc). 

I really like the Intro, Core, Advanced, Pro style but I am not sure how much work it would be to get all of the paths to follow this sort of sectioning.

**Comment by ericdouglas** [comment]
@amorriscode @scamargo I just remember one important thing.

Curriculums' structure may change in the ~near~ future, so we should only use the course name in the folder structure.

Also, we don't need to create all folders upfront, we can create it on demand for the same previous reason.

So the repo structure should be something like:

```
README.md
curriculums/ (?)
    computer-science/
        introduction-to-computer-science-cs50/
            cohort-0001.md
```

**Comment by amorriscode** [comment]
@ericdouglas Makes sense. The only reason I was going to create folders in advanced is so the students could make PRs properly by making a new `cohort-XXXX.md` file and not having to worry about creating the appropriate folder structure above it.

I suppose, in this case, I could make the appropriate folder when new issues come in (if the folder doesn't already exist).

**Comment by ericdouglas** [comment]
@amorriscode yes, we can see when a new issue/cohort is opened so if we don't have the folder we can anticipate and create it. Anyway, it won't be a big deal for the coordinator to create the folder as well.

I believe we can now start to work on the guides itself and after it, create our first cohort.
