### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by ericdouglas** [ossu/roadmap#13]
[Repository](https://github.com/ossu/code-of-conduct).

Please suggest here others code of conduct or ideas to inspire us to create our own code of conduct.

**Comment by waciumawanjohi** [comment]
Will the Code of Conduct allow students to be banned for being ironic?

If the Code of Conduct does allow students to be ironic will the creator of OSS be bound by that code? That is, will past bans of students be subject to review?

**Comment by waciumawanjohi** [comment]
Who is the project manager for the Code of Conduct?
What is the timeline for writing the Code of Conduct?
What will community review and feedback look like?
What will be the process for final approval of the Code of Conduct?

**Comment by ericdouglas** [comment]
OSSU's Code of Conduct was inspired by [FrontendBR forum code of conduct](https://github.com/frontendbr/forum).
